openapi: 3.0.0
info:
  title: some api
paths:
  '/foo/{language}':
    post:
      operationId: somepath 
      summary: does something with a corpus
      parameters:
        - in: path
          name: language
          schema:
            type: string
          required: true
          requestBody:
      description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: #/components/schemas/Corpusonly
      responses:
        '200':
          description: A single value
          content:
            application/json:
              schema:
                $ref: #/components/schemas/Base
components:
    corpusonly:
            type: object
            properties: 
                    Corpusonly: 
                          type: string
                          format: string
